stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive
build:
  stage: build
  script:
    - git submodule init 
    - git submodule update
    - docker-compose --project-name=690_echo_studio up -d
  only:
    - develop
    - triggers
    - ES-1
  tags:
    - echo-studio
