stages:
  - build

build:
  stage: build
  script:
    - git submodule add git@gitlab.pixelplex.by:690-echo-studio/echo-studio-tools.git tools
    - docker-compose --project-name=690_echo_studio down
    - docker-compose --project-name=690_echo_studio up
  only:
    - develop
    - triggers
    - ES-1
  tags:
    - echo-studio
