stages:
  - build
  - deploy

build:
  stage: build
  variables:
    NODE_APP_INSTANCE: $CI_COMMIT_REF_NAME
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master
    - develop
  tags:
    - echo-linux


deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then export PORT=36900; fi
  variables:
    CI_FULL_REGISTRY: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PORT: 26900
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker-compose -p "echo-studio-${CI_COMMIT_REF_NAME}" up -d
  only:
    - develop
    - master
  tags:
    - echo-linux


build.production:
  stage: build
  variables:
    NODE_APP_INSTANCE: production
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - tags
  tags:
    - echo-linux
  environment:
    name: production
    url: https://echostudio.echo.org


deploy.production:
  stage: deploy
  variables:
    NODE_ENV: production
    NODE_APP_INSTANCE: production
    PORT: 16900
    CI_FULL_REGISTRY: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_FULL_REGISTRY
    - docker-compose -p "echo-studio-${CI_COMMIT_REF_NAME}" 690 up -d
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - tags
  tags:
    - echo-studio-1
  when: manual
  environment:
    name: production
    url: https://echostudio.echo.org
