stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive
build:
  stage: build
  script:
    - git submodule add https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.pixelplex.by/690-echo-studio/echo-studio-tools.git tools
    - docker-compose --project-name=690_echo_studio up
  only:
    - develop
    - triggers
    - ES-1
  tags:
    - echo-studio
