stages:
  - build
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursives
build:
  stage: build
  script:
    - docker-compose --project-name=690_echo_studio up
  only:
    - develop
    - triggers
    - ES-1
  tags:
    - echo-studio
